spring:
  application:
    name: finance-access-backend

  datasource:
    url: jdbc:mysql://localhost:3306/financedb?allowPublicKeyRetrieval=true&useSSL=false
    username: root
    password: Vansh@sql16 # please change this to your actual MySQL password
    driver-class-name: com.mysql.cj.jdbc.Driver

  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true
